### ISSUE TITLE
RFC: Migrate Fertilizer uri to decentralized SVG

### ISSUE THREAD

**Issue by PatrickAlphaC** [BeanstalkFarms/Beanstalk#120]
Right now, as part of [fertilizer](0x402c84De2Ce49aF88f5e2eF3710ff89bFED36cB6) contract, the `uri` function returns a result from a centralized server.

Using the following [cast](https://book.getfoundry.sh/) command
```
cast call 0x402c84De2Ce49aF88f5e2eF3710ff89bFED36cB6 "uri" 0 --rpc-url $MAINNET_RPC_URL
```

We get the result:

```
https://fert.bean.money/0
```

Or a more interesting result if we chose an ID like [3452735](https://fert.bean.money/3452735):

```json
{
  "name": "Fertilizer - 3452735",
  "external_url": "https://fert.bean.money/3452735.html",
  "description": "A trusty constituent of any Farmer's toolbox, ERC-1155 FERT has been known to spur new growth on seemingly dead farms. Once purchased and deployed into fertile ground by Farmers, Fertilizer generates new Sprouts: future Beans yet to be repaid by Beanstalk in exchange for doing the work of Replanting the protocol.",
  "image": "https://fert.bean.money/fertilizer.png?1665687752145",
  "attributes": [
    { "trait_type": "Season", "value": 6086 },
    {
      "trait_type": "Humidity",
      "display_type": "boost_percentage",
      "value": 244
    },
    {
      "trait_type": "BPF Remaining",
      "display_type": "boost_number",
      "value": 3.32
    },
    { "trait_type": "Updated At", "display_type": "date", "value": 1665687752 }
  ]
}
```

And each `tokenID` has a similar resulting centralized URL. 

I'd like to propose an SVG pattern instead - since as we know, maintaining a website is both costly and a very very minor centralized attack vector (not worth bug bountying). All the fertilizers could turn into broken jpegs :( 

In the `Internalizer.sol` contract is where the `uri` function lives, which gives us what the images of the fertilizers look like. It's currently defined as such:

```javascript
    function uri(uint256 _id)
        external
        view
        virtual
        override
        returns (string memory)
    {
        return string(abi.encodePacked(_uri, StringsUpgradeable.toString(_id)));
    }
```

Where `_uri` is hard coded to `https://fert.bean.money/`.  

Instead, we could use base64 encoding (one already created by a member of the [Loopring team](https://www.npmjs.com/package/base64-sol)) do something as such:

```javascript
import "base64-sol/base64.sol";
.
.
.
string public constant baseURI = "data:application/json;base64,";

string public constant imageURI = "xxxx";

function uri(uint256 _id)
        external
        view
        virtual
        override
        returns (string memory)
    {
        // return string(abi.encodePacked(_uri, StringsUpgradeable.toString(_id)));
        uint32 season = SeasonFacetAddress.season();
        uint128 humidity = FertilizerFaucetAddress.getHumidity();
        uint128 bpfRemaining = 0; // I'm not sure where this is being pulled from

        return (
            string(
                abi.encodePacked(
                    baseURI,
                    Base64.encode(
                        bytes(
                            abi.encodePacked(
                                '{"name": "Fertilizer - ',
                                StringsUpgradeable.toString(_id),
                                '", external_url": "https://fert.bean.money/3452735.html",  "description": "A trusty constituent of any Farmers toolbox, ERC-1155 FERT has been known to spur new growth on seemingly dead farms. Once purchased and deployed into fertile ground by Farmers, Fertilizer generates new Sprouts: future Beans yet to be repaid by Beanstalk in exchange for doing the work of Replanting the protocol.", "image": "',
                                imageURI,
                                '", "attributes": [{ "trait_type": "Season", "value": ',
                                season,
                                ' },{"trait_type": "Humidity","display_type": "boost_percentage","value": ',
                                humidity,
                                '},{"trait_type": "BPF Remaining","display_type": "boost_number","value": ',
                                bpfRemaining,
                                " },]}"
                                // we don't need "updated at" anymore
                            )
                        )
                    )
                )
            )
        );
    }
```

`imageURI` could be updated at contract deployment time, using a function like:

```javascript
    function svgToImageURI(string memory svg)
        public
        pure
        returns (string memory)
    {
        string memory baseURL = "data:image/svg+xml;base64,";
        string memory svgBase64Encoded = Base64.encode(
            bytes(string(abi.encodePacked(svg)))
        );
        return string(abi.encodePacked(baseURL, svgBase64Encoded));
    }
```

We would just need to pass in an SVG edition of [something like this](https://fert.bean.money/3452735.svg).

Additionally, since that IS already an SVG. We could also update the imageURI at read time based on the on-chain values, and update the image accordingly. I could add some examples for that too if you'd like.

The gas costs to add the whole svg image on-chain might be a little pricey - but it's a one-time cost. 

I've done things like this before, you can see my [examples here](https://github.com/PatrickAlphaC/hardhat-nft-fcc).

**Comment by publiuss** [comment]
@PatrickAlphaC 

Thank you for sharing this RFC. Love the idea of moving Fertilizer metadata on-chain. 

Couple things to note about the metadata–
Fertilizer metadata currently has 3 attributes:
1. `"Season"` – The Season that the Fertilizer was minted.
2. `"Humidity"` – The Humidity during the Season that the Fertilizer was minted.
3. `"BPF Remaining"` – The remaining # of Beans Per Fertilizer that each Fertilizer 

Both (1) and (2) are not stored on-chain, so they would need to be removed if we moved metadata onchain. 

(3) can be computed given a Fertilizer `id`:
```
uint128 bpfRemaining = IBeanstalk(BEANSTALK).bpf() - id;
```

From our perspective, the benefits of moving metadata onchain are worth removing (1) and (2) from metadata given that Fertilizer value is only determined by (3). Also, the high cost of deployment is not a problem.

Please free feel to open up a PR with the change here:
https://github.com/BeanstalkFarms/Beanstalk/blob/master/protocol/contracts/fertilizer/Internalizer.sol#L41

@silochad Can help out with the SVG.

**Comment by PatrickAlphaC** [comment]
Thank you @publiuss, I'll do that!

Curious, do we want to store season and humidity on-chain? It seems like that would be pretty easy to do. Just at mint time, store them in a mapping. It would increase the gas costs of minting, though... and it is purely an aesthetic change.

Thoughts? 

And yes! An SVG of the fertilizer would be great. I can copy the current one but if we can compress the SVG that would be awesome. Don't want to blow gas if we can avoid it.

**Comment by publiuss** [comment]
*Curious, do we want to store season and humidity on-chain?*
Some other things to note: 
- Storing them onchain would require modifying more code–the mint function doesn't need to be modified at all if we don't store them onchain. 
- There are already ~95 different Fertilizer Ids that would need to have their Season + Humidity added onchain retroactively–more code and complexity. 
- For context again increase in gas costs–This would add an `SSTORE` operation that sets a zero to a non-zero value (20,000 Gas) every time a new Fertilizer Id is minted, which occurs the first time Fertilizer is minted after a Season of Rain (P > 1). 

Don't think it's worth it given these reasons and the reasons you mentioned above, but defer to you.

**Comment by PatrickAlphaC** [comment]
I agree. Make sense!

**Comment by silochad** [comment]
@PatrickAlphaC Thanks for opening this RFC. I wanted to highlight some of the motivation for using an off-chain method for rendering these SVGs.

First: the repository that generates and hosts metadata is available at [BeanstalkFarms/Fertilizer-Metadata](https://github.com/BeanstalkFarms/Fertilizer-Metadata) if you're interested in reviewing.

Once an hour, a Cloudflare worker triggers a new deployment, which regenerates SVGs and their corresponding webpages, such as this one: [3_500_000](https://fert.bean.money/3500000.html).

As @publiuss mentioned, some data relevant to each fertilizer is not available on-chain. The number of Beans per Fertilizer ("BPF") remaining to be paid to a particular Fertilizer changes can change between Seasons when Beanstalk mints more Beans. This piece of metadata is important for Farmers to understand when [assessing the value of Fertilizer](https://opensea.io/collection/bean-fertilizer).

We use a combination of subgraph and Beanstalk contract calls to refresh this information each hour after the Sunrise is called. See [here](https://github.com/BeanstalkFarms/Fertilizer-Metadata/blob/7bc39ac9be4d5d9b5db126ce99a291b0d51e931e/src/index.ts#L275) for the relevant metadata generation code, and [here](https://github.com/BeanstalkFarms/Beanstalk-Subgraph/blob/dev/src/FertilizerHandler.ts) for the indexing code used to track transfers of FERT (which is an ERC-1155 token).

IMO: unlike traditional NFTs, the value of Fertilizer isn't derived from its metadata, but rather from how it can be used within Beanstalk, which is already immutable (since it's based on token ID). Using off-chain metadata allows UX improvements without jeopardizing the value of any given FERT.

Here's a zip containing six variations of the SVG, three with text and three without. Let me know if you'd like them in a different format: [Fertilizer SVGs.zip](https://github.com/BeanstalkFarms/Beanstalk/files/9789008/Fertilizer.SVGs.zip)

**Comment by PatrickAlphaC** [comment]
Thanks for the context!

At the end of the day, it's whatever your community wants to do, the benefits of on-chain metadata is that the NFT (EIP-1155) is now truly on-chain. If your server goes down today, everyone will have broken JPEGs!

If you like, we can leave the `external_url` value in the JSON with a link to your server. That way it's more of an optional URI rather than the official one. Then, we can leave a note in the codebase saying that at some point the server will go down, or show people how to query the subgraph themselves or provide a service that does that. 

How's that sound?
