### ISSUE TITLE
New accounts cause crash when hovering over charts

### ISSUE THREAD

**Issue by silochad** [BeanstalkFarms/Beanstalk#193]
**Describe the bug**

If you hover over this chart, website goes blue screen

![image](https://user-images.githubusercontent.com/99763686/204606205-42d59a21-65b5-4caf-a9f4-189e4f560765.png)

**Comment by imcoolbean** [comment]
@silochad can you share steps to replicate?

**Comment by silochad** [comment]
@imcoolbean Pass empty data array into any of the charts and you'll get a crash on hover
