### ISSUE TITLE
Show the number of active proposals in governance page tabs

### ISSUE THREAD

**Issue by silochad** [BeanstalkFarms/Beanstalk#209]
## Description

This would replace the green dots. 

<img width="843" alt="image" src="https://user-images.githubusercontent.com/99763686/185769360-f1f2cc34-5f50-49a7-abd0-28ec1d1a6326.png">

<img width="394" alt="image" src="https://user-images.githubusercontent.com/99763686/185769356-25a43f04-1e59-459e-bc20-1518dec36135.png">

## To discuss

- [ ] Show number of active proposals _or_ the number of active proposals remaining to vote on?

edit: let's do number of active proposals

**Comment by imcoolbean** [comment]
<img width="826" alt="image" src="https://user-images.githubusercontent.com/99687271/219503504-332c9e52-997a-4c2a-918d-0de2e445f0ad.png">
