### ISSUE TITLE
History page UI improvements

### ISSUE THREAD

**Issue by silochad** [BeanstalkFarms/Beanstalk#220]
### Describe the feature you would like
- Organize events into a `DataGrid` or similar structure to allow for filtering and sorting based on event metadata, notably transaction date and amount.
- Silo and Field events are aggregated in their own tab, but not Barn / Market. Add aggregation for all logical sections of Beanstalk.
- Decide on consistent time display: season number, block number, or block timestamp.

### Additional context
`EventItem` duplicates some logic from `EventProcessor`, would be great to come up with one unified API for this kind of thing.

### To discuss
- [ ] DataGrid vs. another data structure

**Comment by hellofromguy** [comment]
deprecated history page for now
