### ISSUE TITLE
UI: Add toggleable markers for past BIPs to all graphs

### ISSUE THREAD

**Issue by silochad** [BeanstalkFarms/Beanstalk#227]
### Describe the feature you would like

Example marker for Replant attached. Replicate this with annotations for each BIP. (Maybe the text only shows on hover?)

<img width="573" alt="image" src="https://user-images.githubusercontent.com/99763686/185511320-a89e705c-0545-460e-aacc-9445df9c3859.png">

**Comment by pizzaman1337** [comment]
Very relevant for past 2 bips :)
