### ISSUE TITLE
Husky

### ISSUE THREAD

**Issue by marshall-bean** [BeanstalkFarms/Beanstalk#241]
- Catalog what we had in original repos, prior to monorepo
- Discuss how to migrate them
- Migrate them to monorepo

**Comment by marshall-bean** [comment]
Cataloged what we had in the original repos, prior to monorepo merge.

## Beanstalk-UI

Pre-commit Linter
Post-checkout generate typechain and graphql query typedef generation

Action: See below. Also need to make sure the necessary yarn scripts moved to the root.

## Beanstalk-SDK

Pre-commit / post-commit scripts to run prettier (bypassed in CI)

Action: See below. Also need to make sure the necessary yarn scripts moved to the root.

I'm not as familiar with husky but from what I can see, we can follow a similar pattern as the GH workflows, that is updating these scripts with conditional logic depending on which project is impacted. E.g. if committing to UI project, only that part of the script runs. Sort of a similar pattern to the existing script from the UI repo https://github.com/BeanstalkFarms/Beanstalk-UI/blob/f4baaafd4f38b1f21e266fbe3d696510a0c889e5/.husky/post-checkout#L10, where we only generate if abis changed. 

I'll do a bit more research on this one.

**Comment by 0xalecks** [comment]
fixed in #253
