### ISSUE TITLE
Amount is different between `PodOrder` and `PodOrderCreated` entities

### ISSUE THREAD

**Issue by silochad** [BeanstalkFarms/Beanstalk#243]
Looks like the historical `podOrderCreateds` event tracking still returns `amount = beanAmount`

```
{
  podOrders(orderBy: createdAt, orderDirection:desc, first:1) {
    id
    podAmount
    beanAmount
  }
  podOrderCreateds(orderBy: createdAt, orderDirection:desc, first:1) {
    amount
  }
}
```

```
{
  "data": {
    "podOrders": [
      {
        "id": "0x44724bcea32e7d5ebc9227d996f5c82be0154e3df6f5828217bc50f60f418d4b",
        "podAmount": "600000000000",
        "beanAmount": "3000000000"
      }
    ],
    "podOrderCreateds": [
      {
        "amount": "3000000000"
      }
    ]
  }
  ```

**Comment by silochad** [comment]
Patched this in the UI manually in #244 but will revert that when subgraph fix is ready to go

**Comment by cujowolf** [comment]
What fix are we looking for here exactly? The `PodOrderCreated` entity stores the raw event info, and that `amount` field now equals the amount of beans.

**Comment by silochad** [comment]
FWIW, blocks are also available on the Argonomics Handbook https://docs.bean.money/developers
