### ISSUE TITLE
Pods chart on Analytics page includes Harvested

### ISSUE THREAD

**Issue by hellofromguy** [BeanstalkFarms/Beanstalk#269]
The Pod Line is only ~772M long, not 830M+. This number seems to include Harvested Pods.

<img width="1210" alt="image" src="https://user-images.githubusercontent.com/28496268/212448229-c2ce9639-e6e2-451f-bbee-24deaa682f11.png">

**Comment by silochad** [comment]
@imcoolbean when you take a look at this can you also head over to the archived Beanstalk-UI repo and check the `git blame` for this part of the code? trying to figure out how this happened (ie. if we ever normalized this value)

Wait actually shouldn't the subgraph be normalizing this? cc @cujowolf

**Comment by imcoolbean** [comment]
Query looks good on FE side so probably need to check that `unharvestablePods` in the subgraph doesn't include harvested. Assigning to @cujowolf.
