### ISSUE TITLE
RFC: Tractor

### ISSUE THREAD

**Issue by publiuss** [BeanstalkFarms/Beanstalk#290]
# RFC: Tractor

**Note that the following information is not completely up to date, but is shared anyway in order to publicize some the thought process and thinking that led to the implementation of Tractor.**

## Summary

- Tractor introduces a generalized peer-to-peer transaction marketplace
- Blueprints are EIP-712 signatures containing generalized on-chain function calls.
- Tractor Functions allow Tractor Operators to perform actions and use assets on behalf of the Publisher.
- Valid Pipe + Boolean Oracles allow Tractor to revert if a given function returns false.

## Abstract

EVM users frequently demand peer-to-peer transactions. Existing peer-to-peer transaction marketplace (Seaport) are limited in the scope of the functionality that they support. Existing generalized function call systems (smart contract accounts, Depot + Pipeline) only support the use of assets from the sender of the transaction. Tractor introduces a generalized function call peer-to-peer transaction marketplace.

## Tractor

Blueprints allow Farmers to create abstracted on-chain function calls, which can be called permissionlessly executed by and receive calldata from other Farmers acting as Tractor Operators

Farmers Publish and Destroy Blueprints. Blueprints are EIP-712 signed payloads containing a publisher, a Farm function call, a set of copy instructions from calldata provided by the Tractor Operator, expiry parameters and the EIP-712 signature from the Publisher. Any Tractor Operator can execute any Blueprint with any calldata at anytime through the `tractor(...)` function provided that the Blueprint does not revert.

Tractor functions (`tractorPlant`, `tractorTransferToken`, etc…) can be added to the farm function call to permit Tractor Operators to perform actions on behalf of the Publisher.

Valid Pipes allows Farmers to create Blueprints that fail if the return value of a permissionless static call to any function fails or returns false. Valid Pipes call Boolean Oracles, which define function calls that return true or false.

## Example

A Farmer wants to `plant` anytime they have more than 100 Plantable Seeds and will pay the caller 1 Earned Bean to call it. (See bottom for solution). A Farmer wants to sell an NFT for Beans.

# Technical Specifications

### Dependencies

- Branch off of `master` branch or later.

## Facets

- New facet– `TractorFacet`.

# Blueprints

Blueprints are EIP-712 signatures containing an arbitrary set of Beanstalk function calls to be executed through Tractor given a set of conditions are true. Any properly signed Blueprint can be executed through Tractor given:

1.  such that `startTime < block.timestamp < endTime` 
2. `blueprintNonce[nonce] < maxNonce`
3. the `farm` function call doesn’t revert

Blueprints are defined by the following struct:

```solidity
struct Blueprint {
  address publisher; // address that published the Blueprint
	bytes data; // a farm function call used by tractor.
	bytes32[] calldataCopyParams; // used to copy callData input by the caller into the functionCall list.
	uint256 maxNonce;
	uint256 startTime;
	uint256 endTime;
	bytes signature;
}
```

Where:

1. `publisher` is the account that published the Blueprint;
2. `data` contains Blueprint `type` and corresponding `typeData`:
    1. Byte 0 contains the Blueprint type;
    2. Bytes 1-n contains the Blueprint type data;
    3. Types:
        1. Type 0: Normal type. Decode into `(bytes[] callData)`; perform normal farm function call (`See `farm()` in `FarmFacet`);
        2. Type 1: Advanced type. Decode into `(bytes[] callData, bytes[] advancedData)` (Or `AdanancedData` struct in `FarmFacet`; perform advanced farm function call (See `advancedFarm()` in FarmFacet);
            
            `(bytes[] callData, bytes[] advancedData)` or `(AdvancedData[] advancedData)`
            
3. `calldataCopyParams` are a set of instructions to allow the caller to input custom data in the `functionCall` structure.
4. `maxNonce` The maximum # of times a blueprint can be executed.
5. `startTime` The timestamp at which the Blueprint can start to be executed.
6. `endTime` The timestamp at which the Blueprint can no longer be executed.
7. `signature` The EIP-712 signature of the Blueprint Hash

## Blueprint Hash

Blueprint Hashes are unique identifiers for Blueprints. Blueprint Hashes are used to track the nonce of a Blueprint and used in the signing process. A Blueprint Hash can be computed by:

```solidity
keccak256(abi.encodePacked(publisher, data, copyDataParams, maxNonce, startTime, endTime));
```

## EIP-712 Signed Blueprints

Only the Blueprint Hash should be used in the EIP-712 in addition to the standard EIP-712 domain.

## Blueprint State

Blueprints are only represented on-chain as a hash. Beanstalk stores a mapping from Blueprint Hash to Blueprint State. 

```solidity
mapping(bytes32 => uint256) blueprintNonce; // 0 for not canceled, 1 for canceled -> by default orders are not canceled.
```

The existence of a non-zero blueprint state 

- `blueprintNonce` → # of times a Blueprint has been executed (`2^uint256` if cancelled).

## Publish Blueprint

Signed Blueprints can be published to Tractor Operators through the `publishBlueprint` function.

**************************************************Note: Blueprints don’t ever have to be published to be executed through Tractor. Publishing a blueprint is just 1 way to post an order publicly.**************************************************

```solidity
function publishBlueprint(Blueprint calldata blueprint) external payable;

event PublishBlueprint(Blueprint blueprint);
```

`publishBlueprint`  does several things:

1. Calculates the Blueprint Hash
2. Verifies the Blueprint signature is correct
3. Emits a `PublishBlueprint` event

## Destroy Blueprint

Blueprints can be canceled at anytime by the Blueprint Publisher by calling `destroyBlueprint`.

```solidity
function destroyBlueprint(Blueprint calldata blueprint) external payable;

event DestroyBlueprint(bytes32 blueprintHash);
```

`destroyBlueprint`  does several things:

1. Calculates the Blueprint Hash
2. Verifies the Blueprint signature is correct.
3. sets `blueprintNonce[blueprintHash] = type(uint256).max;`
4. Emits a `DestroyBlueprint` event.

## Blueprint Nonce

A Blueprint’s nonce can be be fetched through the `blueprintNonce` function.

# Tractor

```solidity
function tractor(
	Blueprint calldata blueprint,
	bytes calldata callData
) external payable;

event Tractor(address operator, bytes32 blueprintHash);
```

Tractor executes a Blueprint. Executing a Blueprint does the following:

1. Calculates the Blueprint Hash
2. Verifies the Blueprint signature is correct.
3. Checks `startTime < block.timestamp < endTime`
4. Checks `blueprintNonce[blueprintHash] < maxNonce`
5. Increments `blueprintNonce[blueprintHash]`
6. Copies `bytes calldata callData` (input as parameter in `tractor(...)`) into `data` using the `calldataCopyParams`
7. Executes the farm function on `data`
8. Parses the Blueprint type by:
    1. Checking for type (0 or 1); and
    2. Decoding the rest of data based on type;
9. Executes the Blueprint by calling `farm` or `advancedFarm`; and
10. Emits a `Tractor` event.

## Tractor Storage

Instead of adding new state variables to `AppStorage`, create a `TractorStorage` library where `TractorStorage` is loaded at slot `keccak256("diamond.storage.Tractor");` (Store as a constant).

```solidity
struct TractorStorage {
	mapping(bytes32 => uint256) blueprintNonce;
	address activePublisher;
}
```

# Tractor Functions

Tractor Functions perform actions on behalf of the Publisher of a Blueprint that that is executed by Tractor. Where as normal functions perform actions for `msg.sender`, tractor functions perform actions for the active publisher. Because `activePublisher` is only set if tractor is being operated and a Blueprint requires the Publisher’s signature, tractorFunctions cannot be called with a user permission.

### Active Publisher

Tractor will use `activePublisher` in TractorStorage to:

1. Determine whether tractor is active
    
    If `activePublisher != address(1)`, then Tractor is active. Otherwise it is not.
    
2. Determine what publisher created the Blueprint currently being operated on.
    
    If Tractor is active, then `activePublisher` will equal the address that created the Blueprint being operated on.
    

Implementing `activePublisher`

1. `InitTractor` should be initialized to `activePublisher = address(1)` for gas efficiency purposes.
2. `tractor(...)` should set `activePublisher = blueprint.publisher` at the start and set `activePublisher = address(1)` at the end

### Implementation

Tractor functions should have the same function signature as their non-tractor alternative and do 2 things:

1. Make sure Tractor is active – `require(activePublisher != address(1));`
2. Perform the action with `activePublisher` as the actor.

## Plant Tractor Example

For example, `plant` is implemented as:

```
function plant() external payable returns (uint256 beans) {
    return _plant(msg.sender);
}
```

`tractorPlant` can be implemented as:

```
function tractorPlant() external payable returns (uint256 beans) {
		address publisher = LibTractor.getBlueprintPublisher();
		require(publisher != address(1));
    return _plant(publisher);
}
```

# Valid Pipe

Add a function to `DepotFacet` called `validPipe` with the following signature:

```solidity
function validPipe(address target, bytes calldata callData);
```

That:

1. performs a static function call on `address target` and `bytes calldata callData`
2. `revert` if the function call reverts
3. `revert` if the function call returns `false`
4. returns the return value of the the function call.

Note: `readPipe` in `DepotFacet` does 1, 2 and 4, but NOT 3.

See: [https://github.com/BeanstalkFarms/Beanstalk/blob/pipeline/protocol/contracts/farm/facets/DepotFacet.sol#L84](https://github.com/BeanstalkFarms/Beanstalk/blob/pipeline/protocol/contracts/farm/facets/DepotFacet.sol#L84)

# Boolean Oracles

Boolean Oracles are auxiliary contracts that contain function calls which return a `boolean`. Tractor calls Boolean Oracles through `requireTruePipe` to verify that on-chain conditions are true. 

### Example:

```solidity

contract CheckEarnedBeanBalanceOracle {

	function checkEarnedBeanBalance(address account, uint256 amount) view returns (boolean) {
		return IBeanstalk(BEANSTALK).balanceOfEarnedBeans(account) >= amount;
	}

}
```

The farmer can them call `requireTruePipe` on the `checkEarnedBeans` function selector at the `CheckEarnedBeanBalanceOracle` `target` address. `account` and `amount`would be encoded in the function call (and could be overwritten through the use of `calldataCopyParams`.

# Plant Tractor

Farmer creates a Blueprint with following publisher, farm and calldataCopyParams

```solidity
publisher: account,
farm: farm(
	validPipe(CHEAK_EARNED_BEANS_ADDRESS, 20_000_000),
	tractorPlant(),
	tractorTransferToken(BEAN, <PASTE IN MSG SENDER>, 1_000_000, 1, <PASTE_IN_TO_MODE>)
),
calldataCopyParams: [
	// Copy msg.sender into the 3rd slot in `transferTokenFor`
	// Copy <PASTE_IN_TO_MODE> into the 5th slot `transferTokenFor`
]
```

**Comment by pizzaman1337** [comment]
Noob question: with the `tractorPlant` example, it looks like any protocol that wants to support Tractor stuff needs to implement tractor-specific functions (`tractorPlant` in this case)? Is it possible to to support other protocols without them having to add tractor-specific functions?
