### ISSUE TITLE
Pod market dust due to rounding

### ISSUE THREAD

**Issue by silochad** [BeanstalkFarms/Beanstalk#302]
Example: this order is fully filled in terms of Pods, but 2E-6 Beans still exist in the order, thus the Subgraph lists it as ACTIVE.

```
{
  "data": {
    "podOrder": {
      "id": "0x12b7fe8066495a24cca5692db93a79af4857032089f700612406b80269644047",
      "status": "ACTIVE",
      "podAmount": "300000000000",
      "beanAmount": "3000000000",
      "podAmountFilled": "300000000000",
      "beanAmountFilled": "2999999998"
    }
  }
}
```

`beanstalk.podOrderById(0x12b7fe8066495a24cca5692db93a79af4857032089f700612406b80269644047) = 2`

**Comment by nickkatsios** [comment]
Is this still a problem? I could work on it.
