### ISSUE TITLE
Discrepancy between Pod Market history and actual values

### ISSUE THREAD

**Issue by silochad** [BeanstalkFarms/Beanstalk#339]
Compare highlighted row to the data in the right sidebar wrt Pod amount (1.46M vs 1,466). Values are multiplied by 1000

![image](https://user-images.githubusercontent.com/99763686/218335642-0f342719-a596-478e-80c3-cf60f066c91f.png)

**Comment by silochad** [comment]
Actual value is shown correctly in the details panel. Confirmed via Louper:
![image](https://user-images.githubusercontent.com/99763686/218335707-620fe0cb-614d-4d9d-92b8-adc0514f2ee2.png)

**Comment by imcoolbean** [comment]
Subgraph [query](https://graph.node.bean.money/subgraphs/name/beanstalk-dev/graphql?query=query+MyQuery+%7B%0A++marketplaceEvents%28%0A++++where%3A+%7Bid%3A+%22podOrderCreated-0xb2006f3aa43315c4ab9f7a6fec13086a8b46188fde6ddd18ecd8a0c4dca7955d-110%22%7D%0A++%29+%7B%0A++++...+on+PodOrderCreated+%7B%0A++++++id%0A++++++pricingType%0A++++++pricingFunction%0A++++++pricePerPod%0A++++++orderId%0A++++++maxPlaceInLine%0A++++++logIndex%0A++++++historyID%0A++++++createdAt%0A++++++hash%0A++++++blockNumber%0A++++++amount%0A++++++account%0A++++%7D%0A++%7D%0A%7D)
