### ISSUE TITLE
Support approval voting on the governance UI

### ISSUE THREAD

**Issue by hellofromguy** [BeanstalkFarms/Beanstalk#349]
**Describe the bug**

Currently the governance page on the UI only supports single choice voting. This means that for single choice votes, a Stalkholder can vote on the proposal without ever exiting the Beanstalk UI. However, with approval voting (which happens with BFCP-Cs), Stalkholders must leave the UI and go to Snapshot in order to vote -- they should be able to select multiple voting choices and vote from the Beanstalk UI.

Here's an example (although the voting period is over): https://app.bean.money/#/governance/0xafac63673dd6eab0e372e55fe66dc5425f026fbcc0f45b025cb0fa74d759181e

**Comment by imcoolbean** [comment]
<img width="543" alt="Screenshot 2023-02-27 at 1 26 25 PM" src="https://user-images.githubusercontent.com/99687271/221663136-9385d3df-49d1-4b2b-897a-e68bcef1cd49.png">
