### ISSUE TITLE
RFC: On-Chain Bug Bounty System

### ISSUE THREAD

**Issue by hellofromguy** [BeanstalkFarms/Beanstalk#390]
# RFC: On-Chain Bug Bounty System

## Proposer

Beanstalk Farms

## Summary

Extend the existing bug bounty structure to include the Homestead, an on-chain bug bounty contract that facilitates the return of assets taken from in-scope Beanstalk ecosystem contracts and the distribution of the corresponding whitehat bounty.

## Problem

Security is paramount to Beanstalk's success and a core focus for Beanstalk Farms.

The Immunefi Bug Bounty Program, established through [BIP-26](https://arweave.net/GnnM7WxvhttHhIKkjffhOHgAQKR6esbjNzIzlnWS8Y4), incentivizes whitehat hackers to find and report bugs in Beanstalk. This initiative has resulted in [multiple bounties](https://snapshot.org/#/beanstalkbugbounty.eth) being awarded for valid bug reports.

However, on its own, this bug bounty program structure is permissioned. Although the program is designed to remove as much subjectivity as possible, ultimately the validity of a report and its corresponding bounty are decided by the [Beanstalk Immunefi Committee (BIC)](https://docs.bean.money/almanac/governance/beanstalk/bic-dashboard). In cases where Farmers’ assets can be stolen directly (critical bugs), this permissioned structure can potentially be unattractive to whitehats and prolong the amount of time that assets are able to be stolen by a malicious actor.

## Proposed Solution

Establish a permissionless on-chain bug bounty system that serves as an alternative to the reward structure for critical bugs in the [Immunefi Bug Bounty Program](https://immunefi.com/bounty/beanstalk/), increasing the probability of potential hackers accepting a whitehat bounty rather than stealing Beanstalk assets.

### Homestead

The Homestead is an on-chain bug bounty contract that allows a whitehat to return assets taken from in-scope Beanstalk ecosystem contracts in exchange for a bounty. 

The Immunefi Bug Bounty Program structure rewards critical bugs with the lower of 10% of practicable economic damage, or $1,100,000 of value (with a minimum reward of $100,000). Upon receipt of assets, the Homestead will automatically return to the sender an amount equivalent to:

> 60% * min(10% of the total amount received, $1,100,000 of value)

The remainder of the value sent to the Homestead is sent to the Beanstalk Community Multisig (BCM). Given the potential friction/downtime introduced by reporting bugs through the Homestead (the BCM must act to return Beanstalk to as close to its original state as possible), it is preferable for whitehats to report bugs through Immunefi. The 40% haircut on the reward reflects this preference.

If the hacker returns all assets taken from the in-scope contracts to the Homestead within 48 hours from their initial removal, by approving this BIP, the Beanstalk DAO considers the amount given to the hacker from the Homestead a whitehat bounty.

Notable cases where whitehats should report critical bugs through Immunefi rather than using the Homestead, outside of getting a higher reward, include:

- Circulating non-Bean assets at risk (the Immunefi Bug Bounty Program rewards these reports at half the normal rate, so using the Homestead in this case doesn’t qualify as a whitehat bounty); and
- The value received by the Homestead would be below $100,000 (whitehats can receive the full minimum reward through Immunefi).

To calculate the whitehat’s reward, the conversion rate of Beans is fixed at 1 Bean to $1 of value. The USD value of all other assets will be determined based on on-chain oracles (TBD).

### Custody

The Homestead contract will be custodied by the BIC Multisig (BICM), a 4-of-6 Safe multisig on which BIC members serve as signers. The BICM will have the unilateral ability to upgrade the Homestead (for example, if the price oracle for a given asset needs to be changed).

After the receipt of assets from the Homestead, the BCM will return the assets to their pre-hack state as soon as practicable via EBIP and/or issue a report to the community detailing the next steps and decisions, if any, that the community must agree on in order to proceed.

### Emergency Hotfixes

The BCM, as established in [BFP-73](https://arweave.net/kD2LfdR4q9ColocqOJTtjkKZCrB3EcTI19DUoNgxhl4), may commit emergency hotfixes to protect Beanstalk in the event of bugs or security vulnerabilities. Alongside fixing the vulnerabilities identified by the hack, restoring assets may require additional changes to Beanstalk. These changes may be made by the BCM as an EBIP as detailed in the [Emergency Response Procedures](https://docs.bean.money/almanac/governance/beanstalk/bcm-process#emergency-response-procedures).

### Contracts in Scope

The *Assets in Scope* section on the Immunefi Bug Bounty Program will serve as the source of assets that qualify for whitehat bounties through the Homestead. The BIC has the ability to add new assets in-scope but otherwise the list of in-scope assets can only be changed via BIP or BOP.

## Rationale

The permissionless, on-chain nature of the Homestead can further incentivize whitehat hackers to identify and report security vulnerabilities rather than stealing funds.

## Contract Changes

None.

## Beans Minted

None.

## Audit

TBD.

## Effective

Immediately upon passage.

**Comment by Joram3** [comment]
#405
