### ISSUE TITLE
UI Bug: Stalk tool-tip on Balances page

### ISSUE THREAD

**Issue by headexpanded** [BeanstalkFarms/Beanstalk#391]
The Stalk tool-tip on the Balances page does not display in normal mode, but does display with the Inspector open.

- Chrome 110.0.5481.177
- https://app.bean.money/#/balances

**Comment by uncoolzero** [comment]
Is this the tooltip you're referring to? It seems to work fine on latest Chrome and other Chrome-based browsers like Brave and Edge

![adfadsf](https://user-images.githubusercontent.com/107518216/228056655-81790615-ad63-41f2-867b-1345e52aa730.png)

**Comment by headexpanded** [comment]
Yeah that's the one, I have no idea why it doesn't work for me unless I have the Inspector open, the others are all fine

**Comment by headexpanded** [comment]
Updated Chrome to Version 111.0.5563.146 (Official Build) (64-bit) and it still happens. No problem on Firefox though.

**Comment by headexpanded** [comment]
Installed brave-browser 1.49.128, and all the tool tips are working. Firefox 111.0.1 (64-bit) all good too. But I still get the same behaviour with that one tool-tip on Chrome 111.0.5563.146 (Official Build) (64-bit)

**Comment by headexpanded** [comment]
Brave:

[brave.webm](https://user-images.githubusercontent.com/108305820/228074475-464032d2-0cc5-4034-9c6a-de6a6bf97917.webm)

Firefox:


[firefox.webm](https://user-images.githubusercontent.com/108305820/228074613-ed4b3ae6-0039-465c-a854-98c1ea3117cb.webm)

Chrome:

[chrome.webm](https://user-images.githubusercontent.com/108305820/228074641-a7494896-602e-409f-bcc3-f16abfa41030.webm)
