### ISSUE TITLE
RFC: EIP-2612 Permit Implementation

### ISSUE THREAD

**Issue by silochad** [BeanstalkFarms/Beanstalk#85]
## Abstract

Add [EIP-2612](https://eips.ethereum.org/EIPS/eip-2612) support for all Beanstalk approvals.

## Motivation

Currently, Beanstalk has two approval systems: 
1. ERC-20 tokens
2. Pods

A third is proposed on #82 for Deposits.
A fourth is proposed on #84 for Farmer function calls like `update()`.

Each approval requires a separate transaction, increasing gas costs and adding friction for Farmers when interacting with Beanstalk.

## Reference implementation

https://eips.ethereum.org/EIPS/eip-2612
https://github.com/Uniswap/v2-core/blob/master/contracts/UniswapV2ERC20.sol
Work began on permits previously on [this branch](https://github.com/BeanstalkFarms/Beanstalk-Replanted/compare/master...add-erc20permit) prior to Beanstalk's Replanting.

## Execution

Estimated development time: 1 week

**Comment by 0xkokonut** [comment]
Hey @silochad,

I'm working on adding an approval system for farm balance and EIP-2612 permit implementation for farm balance + silo deposit. See below for the proposed changes. 

Check out this 2 commits for the implementation:
[Silo deposit permit](https://github.com/BeanstalkFarms/Beanstalk/commit/0dea3506e3e16c4a47e45d68c466289448b6c438)
[Farm balance approval + permit](https://github.com/BeanstalkFarms/Beanstalk/commit/f5d878982e5a3d28f6ad50ab36110cd0b9ba8394)

-------- 


## Abstract

Allow Farmers to delegate the ability to transfer their farm balance to other addresses and add [EIP-2612](https://eips.ethereum.org/EIPS/eip-2612) support for farm balance and silo deposit.

## Motivation

Currently, the only way to transfer farm balance is by calling `transferToken()` on the Farmer's account and there are no ways for farmers to delegate their farm balance to other contracts. Adding an approval system will allow the Farmer's to delegate their farm balance and allows other protocols to build on top of Beanstalk and utilize the farm balance system.

## Specification

Implementation of the farm balance approval system should follow the same pattern as [silo deposit approval system](https://github.com/BeanstalkFarms/Beanstalk/pull/82)

Implementation of the silo deposit/farm balance permit should follow the same pattern as [ERC-20 permit](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/extensions/draft-ERC20Permit.sol)

### Storage

Add the following field into the Account.State struct on `AppStorage.sol`

```
mapping(address => mapping(IERC20 => uint256)) tokenAllowances; // Token allowances
uint256 depositPermitNonces; // A Farmer's current deposit permit nonce
uint256 tokenPermitNonces; // A Farmer's current token permit nonce
```

### New Events

```
event TokenApproval(address indexed owner, address indexed spender, IERC20 token, uint256 amount);
```

### New Functions

#### TokenFacet

```
function transferTokenFrom(
    IERC20 token,
    address sender,
    address recipient,
    uint256 amount,
    LibTransfer.From fromMode,
    LibTransfer.To toMode
) external payable;

function approveToken(
    address spender,
    IERC20 token,
    uint256 amount
) external payable;

function increaseTokenAllowance(
    address spender,
    IERC20 token,
    uint256 addedValue
) public virtual returns (bool);

function decreaseTokenAllowance(
    address spender, 
    IERC20 token,
    uint256 subtractedValue
) public virtual nonReentrant returns (bool);

function tokenAllowance(
    address account, 
    address spender, 
    IERC20 token
) public view virtual returns (uint256);

 function permitToken(
    address owner,
    address spender,
    address token,
    uint256 value,
    uint256 deadline,
    uint8 v,
    bytes32 r,
    bytes32 s
) external payable;

function tokenPermitNonces(address owner)
    public
    view
    virtual
returns (uint256)

function tokenPermitDomainSeparator() external view returns (bytes32);
```

#### SiloFacet

```
function permitDeposits(
    address owner,
    address spender,
    address[] calldata tokens,
    uint256[] calldata values,
    uint256 deadline,
    uint8 v,
    bytes32 r,
    bytes32 s
) external payable

function permitDeposit(
    address owner,
    address spender,
    address token,
    uint256 value,
    uint256 deadline,
    uint8 v,
    bytes32 r,
    bytes32 s
) external payable;

function depositPermitNonces(address owner) public view virtual returns (uint256);

function depositPermitDomainSeparator() external view returns (bytes32);
```

### Modified Functions

#### LibTransfer

```
function transferToken(
    IERC20 token,
    address sender,
    address recipient,
    uint256 amount,
    From fromMode,
    To toMode
) internal returns (uint256 transferredAmount)

```

## Execution

1. Add new functions
2. Modify existings functions
3. Write tests
4. Halborn audit
5. BIP-X

**Comment by hellofromguy** [comment]
Added in BIP-29: https://github.com/BeanstalkFarms/Beanstalk/pull/87
